# Generated by Django 3.0.8 on 2020-07-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200723_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='img_url',
            field=models.CharField(blank=True, default='https://pixabay.com/get/54e1d74a4f54a514f1dc84609620367d1c3ed9e04e507440702b72dc9f45c7_340.jpg', max_length=255),
        ),
    ]
