# Generated by Django 3.0.8 on 2020-07-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200723_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='created',
            field=models.CharField(default='July 24, 2020 09:07:48', max_length=64),
        ),
        migrations.AlterField(
            model_name='auction',
            name='img_url',
            field=models.CharField(blank=True, default='https://us.123rf.com/450wm/pavelstasevich/pavelstasevich1811/pavelstasevich181101028/112815904-stock-vector-no-image-available-icon-flat-vector-illustration.jpg?ver=6', max_length=255),
        ),
    ]
