# Generated by Django 3.0.8 on 2020-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200724_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auction',
            name='created',
            field=models.CharField(default='July 24, 2020 10:29:26', max_length=64),
        ),
    ]
