# Generated by Django 3.0.8 on 2020-07-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200724_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='created',
            field=models.CharField(default='July 24, 2020 10:35:16', max_length=64),
        ),
    ]
