# Generated by Django 3.0.8 on 2020-08-03 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_networkuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkuser',
            name='follower',
            field=models.ManyToManyField(related_name='follower_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='networkuser',
            name='following',
            field=models.ManyToManyField(related_name='following_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='networkuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='network.NetworkUser')),
            ],
        ),
    ]
