# Generated by Django 3.0.8 on 2020-08-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20200803_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='network_user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='network_user',
        ),
    ]
