# Generated by Django 3.0.8 on 2020-08-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20200803_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='network_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='network_user',
            new_name='user',
        ),
    ]
