# Generated by Django 3.1 on 2020-08-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineCourses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='aq',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
